export const TASK_STATUS_VALUES = ["TODO", "IN_PROGRESS", "IN_REVIEW", "BLOCKED", "DONE"] as const;
export const TASK_PRIORITY_VALUES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;

export const LEAVE_STATUS_VALUES = ["PENDING", "APPROVED", "REJECTED", "CANCELLED"] as const;

export const NOTIFICATION_TYPE_VALUES = [
  "TASK_ASSIGNED",
  "TASK_STATUS_CHANGED",
  "TASK_STATUS",
  "LEAVE_APPROVED",
  "LEAVE_REJECTED",
  "LEAVE_CANCELLED",
  "LEAVE_UPDATE",
  "ANNOUNCEMENT",
  "HR_MESSAGE",
  "TEAM_MESSAGE",
  "PROJECT_UPDATE",
  "SYSTEM",
] as const;