export const PERMISSIONS = {
  PLATFORM_DASHBOARD_VIEW: "platform.dashboard.view",
  PLATFORM_ANALYTICS_VIEW: "platform.analytics.view",
  PLATFORM_TENANTS_VIEW: "platform.tenants.view",
  PLATFORM_SETTINGS_VIEW: "platform.settings.view",
  TENANT_DASHBOARD_VIEW: "tenant.dashboard.view",
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_MANAGE: "employees.manage",
  EMPLOYEE_STATUS_MANAGE: "employees.status.manage",
  EMPLOYEE_SKILLS_MANAGE: "employees.skills.manage",
  TEAMS_VIEW: "teams.view",
  TEAMS_MANAGE: "teams.manage",
  TEAM_MEMBERS_MANAGE: "teams.members.manage",
  TEAM_ROLES_MANAGE: "teams.roles.manage",
  PROJECTS_VIEW: "projects.view",
  PROJECTS_MANAGE: "projects.manage",
  PROJECTS_EDIT: "projects.edit",
  PROJECT_DOCUMENTS_MANAGE: "projects.documents.manage",
  TASKS_VIEW: "tasks.view",
  TASKS_MANAGE: "tasks.manage",
  TASKS_ASSIGN: "tasks.assign",
  TASKS_DELETE: "tasks.delete",
  TASK_ATTACHMENTS_MANAGE: "tasks.attachments.manage",
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_MANAGE: "attendance.manage",
  LEAVE_VIEW: "leave.view",
  LEAVE_REQUEST: "leave.request",
  LEAVE_REVIEW: "leave.review",
  LEAVE_ATTACHMENTS_MANAGE: "leave.attachments.manage",
  ANNOUNCEMENTS_VIEW: "announcements.view",
  ANNOUNCEMENTS_MANAGE: "announcements.manage",
  NOTIFICATIONS_VIEW: "notifications.view",
  CHAT_VIEW: "chat.view",
  HR_CHAT_START: "chat.hr.start",
  ANALYTICS_VIEW: "analytics.view",
  PROFILE_VIEW: "profile.view",
  PROFILE_MANAGE: "profile.manage",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_PERMISSION_DENIED_MESSAGE = "You don't have permission";
