import { CalendarRange, Filter, RotateCcw } from 'lucide-react';
import { useAnalyticsFilterStore } from '@/store/analyticsFilterStore';
import type { BusinessIntelligenceData, AnalyticsFilters } from '@/modules/analytics/types';

const presets = [{ id: 'today', label: 'Today' }, { id: 'week', label: 'This week' }, { id: 'month', label: 'This month' }, { id: 'quarter', label: 'Quarter' }, { id: 'year', label: 'Year' }] as const;

export function BiFilterBar({ options }: { options?: BusinessIntelligenceData['filterOptions'] }) {
  const { filters, setFilter, setNamedPreset, reset } = useAnalyticsFilterStore();
  const select = (key: keyof AnalyticsFilters, title: string, items: Array<{ value: string; label: string }>) => <label className='min-w-36 flex-1'><span className='mb-1 block text-[10px] font-bold uppercase tracking-wider' style={{ color: 'var(--text-tertiary)' }}>{title}</span><select value={filters[key]} onChange={(event) => setFilter(key, event.target.value)} className='h-10 w-full rounded-xl border px-3 text-xs outline-none' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)', color: 'var(--text-primary)' }}><option value=''>All {title}</option>{items.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>;
  return <section className='rounded-2xl border p-3 shadow-lg backdrop-blur-xl print:hidden' style={{ background: 'color-mix(in srgb,var(--bg-surface) 88%,transparent)', borderColor: 'var(--border-default)' }}>
    <div className='flex flex-wrap items-center gap-2'><span className='inline-flex items-center gap-2 px-2 text-xs font-bold' style={{ color: 'var(--text-secondary)' }}><Filter size={15} className='text-purple-600' />Global filters</span><div className='flex max-w-full gap-1 overflow-x-auto rounded-xl border p-1' style={{ borderColor: 'var(--border-default)' }}>{presets.map((preset) => <button key={preset.id} onClick={() => setNamedPreset(preset.id)} className='whitespace-nowrap rounded-lg px-2.5 py-1.5 text-[11px] font-semibold hover:bg-purple-500/10'>{preset.label}</button>)}</div><button onClick={reset} className='ml-auto inline-flex h-9 items-center gap-1.5 rounded-xl border px-3 text-xs font-semibold' style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}><RotateCcw size={13} />Reset</button></div>
    <div className='mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-6'><label><span className='mb-1 block text-[10px] font-bold uppercase tracking-wider' style={{ color: 'var(--text-tertiary)' }}>From date</span><span className='relative block'><CalendarRange className='absolute left-3 top-2.5 text-purple-500' size={15} /><input type='date' value={filters.fromDate} onChange={(event) => setFilter('fromDate', event.target.value)} className='h-10 w-full rounded-xl border pl-9 pr-2 text-xs' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)', color: 'var(--text-primary)' }} /></span></label><label><span className='mb-1 block text-[10px] font-bold uppercase tracking-wider' style={{ color: 'var(--text-tertiary)' }}>To date</span><span className='relative block'><CalendarRange className='absolute left-3 top-2.5 text-purple-500' size={15} /><input type='date' value={filters.toDate} onChange={(event) => setFilter('toDate', event.target.value)} className='h-10 w-full rounded-xl border pl-9 pr-2 text-xs' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)', color: 'var(--text-primary)' }} /></span></label>
      {select('department', 'Department', options?.departments ?? [])}{select('teamId', 'Team', options?.teams ?? [])}{select('employeeId', 'Employee', options?.employees ?? [])}{select('projectId', 'Project', options?.projects ?? [])}{select('status', 'Task status', options?.taskStatuses ?? [])}{select('recruitmentStatus', 'Recruitment', options?.recruitmentStatuses ?? [])}{select('attendancePeriod', 'Attendance period', [{ value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }, { value: 'monthly', label: 'Monthly' }])}{select('leaveType', 'Leave type', options?.leaveTypes ?? [])}
    </div>
  </section>;
}
