import { lazy, Suspense, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Activity, BarChart3, Bell, BriefcaseBusiness, CalendarCheck2, CheckSquare2, FileBarChart2, FolderKanban, RefreshCw, ShieldAlert, Sparkles, Users, UsersRound } from 'lucide-react';
import { useBusinessIntelligenceQuery, useTenantAnalyticsQuery, useTenantDashboardQuery } from '@/hooks/queries/useDashboardQueries';
import { useAuthStore } from '@/store/authStore';
import { normalizeAppRole } from '@/constants/rolePermissionMap';
import { tenantRoutes } from '@/utils/tenantRoutes';
import { BiFilterBar } from '@/modules/analytics/components/BiFilterBar';
import { BiKpiCard } from '@/modules/analytics/components/BiKpiCard';
import { ReportExportMenu } from '@/modules/analytics/components/ReportExportMenu';
import { ErrorState, LoadingSkeleton } from '@/components/common/AsyncStates';
import { SectionCard } from '@/components/common/SectionCard';
import type { BiChartPoint, BiMetric, BusinessIntelligenceData, TenantAnalyticsData, TenantDashboardSnapshot } from '@/modules/analytics/types';
import type { BiChartVariant, BiSeries } from '@/modules/analytics/components/BiChartCard';

const BiChartCard = lazy(() => import('@/modules/analytics/components/BiChartCard'));
type Domain = 'overview' | 'employees' | 'projects' | 'tasks' | 'attendance' | 'leave' | 'recruitment' | 'teams' | 'system';
const domains: Array<{ id: Domain; label: string }> = [{ id: 'overview', label: 'Executive' }, { id: 'employees', label: 'Employees' }, { id: 'projects', label: 'Projects' }, { id: 'tasks', label: 'Tasks' }, { id: 'attendance', label: 'Attendance' }, { id: 'leave', label: 'Leave' }, { id: 'recruitment', label: 'Recruitment' }, { id: 'teams', label: 'Teams' }, { id: 'system', label: 'System health' }];

export function BusinessIntelligenceCenter({ mode }: { mode: 'analytics' | 'reports' }) {
  const params = useParams();
  const role = normalizeAppRole(useAuthStore((state) => state.user?.role));
  const allowed = role === 'TENANT_ADMIN' || role === 'HR';
  const query = useBusinessIntelligenceQuery(allowed);
  if (role === 'MANAGER' || role === 'EMPLOYEE') return <ScopedAnalyticsCenter role={role} />;
  const visibleDomains = role === 'HR' ? domains.filter((item) => ['employees', 'attendance', 'leave', 'recruitment'].includes(item.id)) : domains;
  const domain = (visibleDomains.some((item) => item.id === params.domain) ? params.domain : visibleDomains[0]?.id ?? 'overview') as Domain;
  const base = mode === 'reports' ? tenantRoutes.reports() : tenantRoutes.analytics();
  if (!allowed) return <SectionCard title='Business Intelligence Center' subtitle='Company-wide intelligence is governed by tenant administration.'><p className='text-sm' style={{ color: 'var(--text-secondary)' }}>Your Manager workspace remains scoped to operational dashboards. Ask a Tenant Admin for an exported company report when required.</p></SectionCard>;
  return <div className='space-y-5 pb-8'>
    <header className='relative overflow-hidden rounded-3xl border p-6 shadow-xl sm:p-8' style={{ background: 'linear-gradient(125deg,color-mix(in srgb,#9332ea 18%,var(--bg-surface)),color-mix(in srgb,#2563eb 9%,var(--bg-surface)) 65%,var(--bg-surface))', borderColor: 'rgba(147,50,234,.28)' }}><span className='absolute -right-20 -top-28 h-72 w-72 rounded-full bg-purple-500/15 blur-3xl' /><span className='absolute bottom-0 left-1/3 h-32 w-48 rounded-full bg-blue-500/10 blur-3xl' /><div className='relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between'><div><span className='inline-flex items-center gap-2 rounded-full border border-purple-500/20 bg-purple-500/10 px-3 py-1 text-xs font-bold text-purple-600'><Sparkles size={13} />WorkNest Intelligence Cloud</span><h1 className='mt-4 text-2xl font-extrabold tracking-tight sm:text-3xl' style={{ color: 'var(--text-primary)' }}>{mode === 'reports' ? 'Reporting & Analytics Center' : 'Business Intelligence Center'}</h1><p className='mt-2 max-w-2xl text-sm leading-6' style={{ color: 'var(--text-secondary)' }}>A live command center for workforce health, delivery performance, talent, capacity, and operational risk.</p>{query.data && <p className='mt-3 inline-flex items-center gap-1.5 text-[11px] font-semibold text-emerald-600'><Activity size={13} />Live · refreshed {new Date(query.data.generatedAt).toLocaleTimeString()}</p>}</div><div className='flex flex-wrap gap-2 print:hidden'>{query.data && <ReportExportMenu report={{ title: 'WorkNest executive BI report', headers: ['KPI', 'Value', 'Context'], rows: query.data.kpis.map((item) => [item.label, `${item.value}${item.unit}`, item.context]) }} />}<button onClick={() => void query.refetch()} className='inline-flex h-9 items-center gap-2 rounded-xl bg-purple-600 px-3 text-xs font-bold text-white shadow-lg shadow-purple-500/20'><RefreshCw size={14} className={query.isFetching ? 'animate-spin' : ''} />Refresh</button></div></div></header>
    <nav className='scrollbar-hide flex gap-1 overflow-x-auto rounded-2xl border p-1.5 print:hidden' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)' }}>{visibleDomains.map((item) => <Link key={item.id} to={item.id === 'overview' ? base : `${base}/${item.id}`} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-bold transition ${domain === item.id ? 'bg-purple-600 text-white shadow-md shadow-purple-500/20' : 'hover:bg-purple-500/10'}`} style={domain === item.id ? undefined : { color: 'var(--text-secondary)' }}>{item.label}</Link>)}</nav>
    <BiFilterBar options={query.data?.filterOptions} />
    {query.isLoading && <LoadingView />}
    {query.isError && <ErrorState message='Unable to load the governed BI snapshot.' onRetry={() => void query.refetch()} />}
    {query.data && <Dashboard domain={domain} data={query.data} />}
  </div>;
}

function ScopedAnalyticsCenter({ role }: { role: 'MANAGER' | 'EMPLOYEE' }) {
  const analytics = useTenantAnalyticsQuery();
  const snapshot = useTenantDashboardQuery();
  const loading = analytics.isLoading || snapshot.isLoading;
  if (loading) return <LoadingView />;
  if (analytics.isError || snapshot.isError || !analytics.data || !snapshot.data) return <ErrorState message='Unable to load your scoped analytics workspace.' onRetry={() => { void analytics.refetch(); void snapshot.refetch(); }} />;
  return <div className='space-y-6 pb-8'><header className='relative overflow-hidden rounded-3xl border p-7 shadow-xl' style={{ background: 'linear-gradient(125deg,color-mix(in srgb,#9332ea 17%,var(--bg-surface)),color-mix(in srgb,#2563eb 8%,var(--bg-surface)))', borderColor: 'rgba(147,50,234,.25)' }}><span className='absolute -right-16 -top-20 h-56 w-56 rounded-full bg-purple-500/15 blur-3xl' /><div className='relative'><span className='inline-flex items-center gap-2 rounded-full bg-purple-500/10 px-3 py-1 text-xs font-bold text-purple-600'><BarChart3 size={13} />{role === 'MANAGER' ? 'Manager Intelligence' : 'My Analytics'}</span><h1 className='mt-3 text-2xl font-extrabold'>{role === 'MANAGER' ? 'Team performance command center' : 'Personal productivity overview'}</h1><p className='mt-1 text-sm' style={{ color: 'var(--text-secondary)' }}>{role === 'MANAGER' ? 'Team-scoped workload, delivery progress, deadlines, and capacity signals.' : 'Your tasks, attendance, leave utilization, and completion statistics in one private view.'}</p></div></header><ScopedDashboard role={role} data={analytics.data} snapshot={snapshot.data} /></div>;
}

function ScopedDashboard({ role, data, snapshot }: { role: 'MANAGER' | 'EMPLOYEE'; data: TenantAnalyticsData; snapshot: TenantDashboardSnapshot }) {
  const taskTotal = data.taskStatusDistribution.reduce((sum, item) => sum + item.value, 0);
  const done = data.taskStatusDistribution.find((item) => item.label === 'Done')?.value ?? snapshot.completedTasks;
  const completion = taskTotal ? Math.round(done * 100 / taskTotal) : 0;
  const attendance = snapshot.attendanceSummary;
  const metrics: BiMetric[] = role === 'MANAGER' ? [
    roleMetric('open', 'Open team tasks', data.openTasks, 'Work currently in progress', 'blue'),
    roleMetric('completion', 'Completion rate', completion, 'Task delivery in visible scope', 'green', '%'),
    roleMetric('overdue', 'Overdue work', data.overdueTasks.length, 'Requires owner action', data.overdueTasks.length ? 'red' : 'green'),
    roleMetric('projects', 'Active projects', data.activeProjects, 'Visible delivery portfolio', 'purple'),
    roleMetric('teams', 'Teams in scope', data.teamWorkload.length, 'Workload-bearing teams', 'purple'),
  ] : [
    roleMetric('assigned', 'Assigned tasks', taskTotal, 'Your visible task portfolio', 'purple'),
    roleMetric('open', 'Open tasks', data.openTasks, 'Still requiring completion', 'blue'),
    roleMetric('completion', 'Completion rate', completion, 'Personal delivery rate', 'green', '%'),
    roleMetric('attendance', 'Attendance status', attendance.myWorkedMinutes, `${attendance.myTodayStatus.replaceAll('_', ' ')} today`, attendance.myTodayStatus === 'ABSENT' ? 'red' : 'green', ' min'),
    roleMetric('leave', 'Pending leave', data.pendingLeaves, 'Awaiting a decision', 'amber'),
  ];
  const attendancePoints: BiChartPoint[] = [{ label: 'Present', value: attendance.present, secondaryValue: null, tertiaryValue: null, id: null }, { label: 'Late', value: attendance.late, secondaryValue: null, tertiaryValue: null, id: null }, { label: 'Absent', value: attendance.absent, secondaryValue: null, tertiaryValue: null, id: null }, { label: 'Half day', value: attendance.halfDay, secondaryValue: null, tertiaryValue: null, id: null }];
  type ScopedChart = { title: string; subtitle: string; data: Array<{ label: string; value: number; id?: string | null; secondaryValue?: number | null }>; variant: BiChartVariant; insight: string; route: (point: BiChartPoint) => string; unit?: string };
  const charts: ScopedChart[] = role === 'MANAGER' ? [
    { title: 'Task progress', subtitle: 'Visible work by workflow status', data: data.taskStatusDistribution, variant: 'donut' as const, insight: `${completion}% of visible work is complete.`, route: (point: BiChartPoint) => `${tenantRoutes.tasks()}?status=${point.label.replaceAll(' ', '_').toUpperCase()}` },
    { title: 'Project progress', subtitle: 'Task completion by project', data: data.projectProgress, variant: 'horizontalBar' as const, insight: 'Use low-progress projects to prioritize the next delivery review.', route: (point: BiChartPoint) => point.id ? tenantRoutes.projectDetail(point.id) : tenantRoutes.projects(), unit: '%' },
    { title: 'Team workload', subtitle: 'Open work distributed across teams', data: data.teamWorkload, variant: 'horizontalBar' as const, insight: 'Rebalance assignments where workload is concentrated in one team.', route: () => tenantRoutes.teams() },
    { title: 'Resource utilization', subtitle: 'Assigned work by employee', data: data.workloadByEmployee, variant: 'bar' as const, insight: 'High assignment concentration is an early resource-utilization risk.', route: () => tenantRoutes.tasks() },
  ] : [
    { title: 'My task completion', subtitle: 'Assigned tasks by workflow status', data: data.taskStatusDistribution, variant: 'donut' as const, insight: `${completion}% of your assigned work is complete.`, route: (point: BiChartPoint) => `${tenantRoutes.tasks()}?status=${point.label.replaceAll(' ', '_').toUpperCase()}` },
    { title: 'My attendance', subtitle: 'Personal attendance summary', data: attendancePoints, variant: 'bar' as const, insight: `${attendance.myWorkedMinutes} minutes recorded today.`, route: () => tenantRoutes.attendance() },
    { title: 'My leave history', subtitle: 'Leave requests by decision status', data: data.leaveStatusDistribution, variant: 'donut' as const, insight: `${data.pendingLeaves} request${data.pendingLeaves === 1 ? '' : 's'} currently await a decision.`, route: () => tenantRoutes.leave() },
  ];
  return <><section><SectionTitle eyebrow={role === 'MANAGER' ? 'Team KPIs' : 'Personal KPIs'} title={role === 'MANAGER' ? 'Performance and capacity' : 'My current performance'} /><div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5'>{metrics.map((metric) => <BiKpiCard key={metric.key} metric={metric} icon={metricIcon(metric.key)} />)}</div></section><section><SectionTitle eyebrow='Trend analysis' title={role === 'MANAGER' ? 'Team decision signals' : 'Personal activity signals'} /><div className='grid gap-5 xl:grid-cols-2'>{charts.map((chart) => <Suspense key={chart.title} fallback={<LoadingSkeleton lines={7} className='h-96' />}><BiChartCard title={chart.title} subtitle={chart.subtitle} data={chart.data.map((item) => ({ ...item, secondaryValue: item.secondaryValue ?? null, tertiaryValue: null, id: item.id ?? null }))} variant={chart.variant} insight={chart.insight} drillDown={chart.route} unit={chart.unit} /></Suspense>)}</div></section><section><SectionTitle eyebrow='Decision support' title='Insights and upcoming risks' /><div className='grid gap-4 lg:grid-cols-2'>{data.insights.map((insight) => <div key={insight.id} className='rounded-2xl border p-4' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)' }}><Sparkles size={17} className='text-purple-600' /><strong className='mt-2 block text-sm'>{insight.title}</strong><p className='mt-1 text-xs leading-5' style={{ color: 'var(--text-secondary)' }}>{insight.description}</p></div>)}</div></section></>;
}

function roleMetric(key: string, label: string, value: number, context: string, tone: string, unit = ''): BiMetric { return { key, label, value, context, tone, unit, changePercent: null }; }

function LoadingView() { return <div className='space-y-5'><div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-4'><LoadingSkeleton lines={3} className='h-40' /><LoadingSkeleton lines={3} className='h-40' /><LoadingSkeleton lines={3} className='h-40' /><LoadingSkeleton lines={3} className='h-40' /></div><div className='grid gap-5 xl:grid-cols-2'><LoadingSkeleton lines={8} className='h-96' /><LoadingSkeleton lines={8} className='h-96' /></div></div>; }

function Dashboard({ domain, data }: { domain: Domain; data: BusinessIntelligenceData }) {
  const keys: Record<Domain, string[]> = {
    overview: ['employees', 'runningProjects', 'openTasks', 'overdueTasks', 'attendanceRate', 'pendingLeave', 'openJobs', 'hires', 'teams', 'unreadNotifications'],
    employees: ['employees', 'activeEmployees', 'newEmployees'], projects: ['projects', 'runningProjects', 'completedProjects', 'projectHealth'], tasks: ['openTasks', 'completedTasks', 'blockedTasks', 'overdueTasks'], attendance: ['attendanceRate', 'presentToday', 'lateToday', 'absentToday'], leave: ['pendingLeave', 'approvedLeave', 'averageLeave'], recruitment: ['openJobs', 'applications', 'interviews', 'hires', 'acceptanceRate'], teams: ['teams', 'largestTeam', 'averageTeam'], system: ['notifications', 'announcements', 'unreadNotifications'],
  };
  const metrics = data.kpis.filter((metric) => keys[domain].includes(metric.key));
  return <div className='space-y-6'><section><SectionTitle eyebrow='Live performance' title={`${domains.find((item) => item.id === domain)?.label} key indicators`} /><div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5'>{metrics.map((metric) => <BiKpiCard key={metric.key} metric={metric} icon={metricIcon(metric.key)} />)}</div></section>{domain === 'overview' && <RiskAndInsight data={data} />}<ChartGrid domain={domain} data={data} />{(domain === 'system' || domain === 'overview') && <ActivityTable data={data} />}{domain !== 'overview' && <RiskAndInsight data={data} />}</div>;
}

function ChartGrid({ domain, data }: { domain: Domain; data: BusinessIntelligenceData }) {
  const configs = chartConfigs(data).filter((item) => item.domains.includes(domain));
  return <section><SectionTitle eyebrow='Visual analytics' title='Interactive decision signals' /><div className='grid gap-5 xl:grid-cols-2'>{configs.map((config) => <Suspense key={config.key} fallback={<LoadingSkeleton lines={7} className='h-96' />}><BiChartCard title={config.title} subtitle={config.subtitle} data={config.data} variant={config.variant} insight={config.insight} series={config.series} unit={config.unit} drillDown={config.drillDown} /></Suspense>)}</div></section>;
}

interface ChartConfig { key: string; domains: Domain[]; title: string; subtitle: string; data: BiChartPoint[]; variant: BiChartVariant; insight: string; series?: BiSeries[]; unit?: string; drillDown?: (point: BiChartPoint) => string; }
function chartConfigs(data: BusinessIntelligenceData): ChartConfig[] {
  const chart = (key: string) => data.charts[key] ?? [];
  const top = (key: string) => chart(key).reduce<BiChartPoint | undefined>((best, item) => !best || item.value > best.value ? item : best, undefined);
  const path = (base: string, key: string, point: BiChartPoint) => `${base}?${new URLSearchParams({ [key]: point.id ?? point.label.replaceAll(' ', '_').toUpperCase() })}`;
  const healthMetric = data.kpis.find((item) => item.key === 'projectHealth');
  const health: BiChartPoint[] = [{ label: 'Project health', value: healthMetric?.value ?? 0, secondaryValue: null, tertiaryValue: null, id: null }];
  return [
    { key: 'employeeGrowth', domains: ['employees'], title: 'Employee joining trend', subtitle: 'New employees joining over the selected period', data: chart('employeeGrowth'), variant: 'area', insight: `${top('employeesByDepartment')?.label ?? 'No department'} currently has the largest workforce footprint.`, drillDown: () => tenantRoutes.employees() },
    { key: 'employeesByDepartment', domains: ['overview', 'employees'], title: 'Employees by department', subtitle: 'Workforce allocation across business functions', data: chart('employeesByDepartment'), variant: 'donut', insight: `${top('employeesByDepartment')?.label ?? 'No department'} is the largest department in the current organization.`, drillDown: (point) => path(tenantRoutes.employees(), 'department', point) },
    { key: 'employeesByDesignation', domains: ['employees'], title: 'Employees by designation', subtitle: 'Capability mix and role concentration', data: chart('employeesByDesignation'), variant: 'horizontalBar', insight: `${top('employeesByDesignation')?.label ?? 'No designation'} is the most common designation.`, drillDown: (point) => path(tenantRoutes.employees(), 'search', point) },
    { key: 'employeeStatus', domains: ['employees'], title: 'Employee status', subtitle: 'Active and inactive workforce composition', data: chart('employeeStatus'), variant: 'pie', insight: 'Use inactive workforce share as an early signal for account hygiene and capacity planning.', drillDown: (point) => path(tenantRoutes.employees(), 'status', point) },
    { key: 'projectsByStatus', domains: ['overview', 'projects'], title: 'Projects by status', subtitle: 'Portfolio distribution and delivery state', data: chart('projectsByStatus'), variant: 'donut', insight: `${top('projectsByStatus')?.label ?? 'No status'} is the dominant portfolio state.`, drillDown: (point) => path(tenantRoutes.projects(), 'status', point) },
    { key: 'projectProgress', domains: ['projects'], title: 'Project progress', subtitle: 'Task-based completion percentage by project', data: chart('projectProgress'), variant: 'horizontalBar', unit: '%', insight: 'Projects with low completion and near-term commitments should be reviewed in the next portfolio meeting.', drillDown: (point) => point.id ? tenantRoutes.projectDetail(point.id) : tenantRoutes.projects() },
    { key: 'projectsCreated', domains: ['projects'], title: 'Projects created per month', subtitle: 'Demand entering the delivery portfolio', data: chart('projectsCreated'), variant: 'line', insight: 'Compare project intake with team capacity before committing new delivery dates.', drillDown: () => tenantRoutes.projects() },
    { key: 'projectHealth', domains: ['projects'], title: 'Project health score', subtitle: 'Completion-weighted portfolio signal', data: health, variant: 'gauge', unit: '%', insight: `${health[0].value}% health reflects current task completion across the selected scope.`, drillDown: () => tenantRoutes.projects() },
    { key: 'tasksByStatus', domains: ['overview', 'tasks'], title: 'Tasks by status', subtitle: 'Work distribution across the delivery workflow', data: chart('tasksByStatus'), variant: 'donut', insight: `${top('tasksByStatus')?.label ?? 'No status'} contains the largest task volume.`, drillDown: (point) => path(tenantRoutes.tasks(), 'status', point) },
    { key: 'taskPriority', domains: ['tasks'], title: 'Task priority mix', subtitle: 'Urgency profile of current work', data: chart('taskPriority'), variant: 'bar', insight: 'A growing high-priority share can indicate planning instability or overloaded delivery teams.', drillDown: (point) => path(tenantRoutes.tasks(), 'priority', point) },
    { key: 'taskCompletionTrend', domains: ['tasks'], title: 'Task completion trend', subtitle: 'Completed work compared with total activity', data: chart('taskCompletionTrend'), variant: 'line', insight: 'Sustained separation between total activity and completions signals accumulating work in progress.', series: [{ key: 'value', label: 'Completed', color: '#10b981' }, { key: 'secondaryValue', label: 'Total', color: '#9332ea' }], drillDown: () => tenantRoutes.tasks() },
    { key: 'teamWorkload', domains: ['tasks', 'teams'], title: 'Team workload', subtitle: 'Open work currently assigned to each team', data: chart('teamWorkload'), variant: 'horizontalBar', insight: `${top('teamWorkload')?.label ?? 'No team'} carries the largest open workload.`, drillDown: (point) => path(tenantRoutes.tasks(), 'team', point) },
    { key: 'attendanceTrend', domains: ['overview', 'attendance'], title: 'Attendance trend', subtitle: 'Present, late, and absent records by day', data: chart('attendanceTrend'), variant: 'area', insight: 'Watch for repeated late-arrival spikes; they often reveal team-level scheduling friction.', series: [{ key: 'value', label: 'Present', color: '#10b981' }, { key: 'secondaryValue', label: 'Late', color: '#f59e0b' }, { key: 'tertiaryValue', label: 'Absent', color: '#ef4444' }], drillDown: () => tenantRoutes.attendance() },
    { key: 'leaveTypes', domains: ['leave'], title: 'Leave type distribution', subtitle: 'Demand by leave category', data: chart('leaveTypes'), variant: 'pie', insight: `${top('leaveTypes')?.label ?? 'No leave type'} is the most requested leave category.`, drillDown: (point) => path(tenantRoutes.leave(), 'type', point) },
    { key: 'leaveTrend', domains: ['leave'], title: 'Leave trend and approvals', subtitle: 'Requests compared with approvals by month', data: chart('leaveTrend'), variant: 'area', insight: 'A widening gap between requests and approvals can indicate a decision backlog.', series: [{ key: 'value', label: 'Requests', color: '#9332ea' }, { key: 'secondaryValue', label: 'Approved', color: '#10b981' }], drillDown: () => tenantRoutes.leave() },
    { key: 'recruitmentPipeline', domains: ['overview', 'recruitment'], title: 'Recruitment conversion funnel', subtitle: 'Candidate movement from application to hire', data: chart('recruitmentPipeline'), variant: 'funnel', insight: 'The largest stage-to-stage drop identifies the next recruiting process bottleneck.', drillDown: (point) => path(tenantRoutes.recruitmentApplications(), 'status', point) },
    { key: 'applicationsByJob', domains: ['recruitment'], title: 'Applications per job', subtitle: 'Candidate demand by open position', data: chart('applicationsByJob'), variant: 'horizontalBar', insight: `${top('applicationsByJob')?.label ?? 'No position'} attracts the largest applicant pool.`, drillDown: () => tenantRoutes.recruitmentApplications() },
    { key: 'hiringTrend', domains: ['recruitment'], title: 'Hiring trend', subtitle: 'Successful hires by month', data: chart('hiringTrend'), variant: 'line', insight: 'Compare hiring momentum with open job demand to forecast recruiting capacity.', drillDown: () => tenantRoutes.recruitmentApplications() },
    { key: 'teamSizes', domains: ['teams'], title: 'Team member distribution', subtitle: 'Active membership across teams', data: chart('teamSizes'), variant: 'radar', insight: `${top('teamSizes')?.label ?? 'No team'} is the largest collaboration unit.`, drillDown: (point) => point.id ? tenantRoutes.teamDetail(point.id) : tenantRoutes.teams() },
    { key: 'notificationVolume', domains: ['system'], title: 'Notification volume', subtitle: 'System messaging generated by month', data: chart('notificationVolume'), variant: 'line', insight: 'Rapid notification growth should be checked for alert fatigue and duplicate workflows.', drillDown: () => tenantRoutes.notifications() },
    { key: 'announcementVolume', domains: ['system'], title: 'Announcements created', subtitle: 'Company communication cadence', data: chart('announcementVolume'), variant: 'bar', insight: 'Regular announcement cadence keeps operational changes visible without overwhelming teams.', drillDown: () => tenantRoutes.announcements() },
  ];
}

function RiskAndInsight({ data }: { data: BusinessIntelligenceData }) { return <section className='grid gap-5 xl:grid-cols-[1fr_1.25fr]'><div><SectionTitle eyebrow='Risk radar' title='Warnings requiring action' /><div className='space-y-3'>{data.risks.length ? data.risks.map((risk) => <Link key={risk.id} to={`${tenantRoutes.path(risk.route)}`} className='flex items-start gap-3 rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-lg' style={{ borderColor: risk.severity === 'critical' ? 'rgba(220,38,38,.3)' : 'rgba(217,119,6,.3)', background: risk.severity === 'critical' ? 'rgba(220,38,38,.07)' : 'rgba(217,119,6,.07)' }}><span className={`rounded-xl p-2 ${risk.severity === 'critical' ? 'bg-red-500/10 text-red-600' : 'bg-amber-500/10 text-amber-600'}`}><ShieldAlert size={18} /></span><span><strong className='block text-sm' style={{ color: 'var(--text-primary)' }}>{risk.count} · {risk.title}</strong><span className='mt-1 block text-xs leading-5' style={{ color: 'var(--text-secondary)' }}>{risk.description}</span></span></Link>) : <div className='rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5 text-sm text-emerald-600'>No critical operating risks were detected in this scope.</div>}</div></div><div><SectionTitle eyebrow='Smart recommendations' title='Decision intelligence' /><div className='grid gap-3 sm:grid-cols-2'>{data.insights.map((insight) => <Link key={insight.id} to={insight.route ? tenantRoutes.path(insight.route) : tenantRoutes.analytics()} className='rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-lg' style={{ background: 'var(--bg-surface)', borderColor: 'var(--border-default)' }}><Sparkles size={16} className='text-purple-600' /><strong className='mt-3 block text-sm' style={{ color: 'var(--text-primary)' }}>{insight.title}</strong><span className='mt-1 block text-xs leading-5' style={{ color: 'var(--text-secondary)' }}>{insight.description}</span></Link>)}</div></div></section>; }

function ActivityTable({ data }: { data: BusinessIntelligenceData }) { return <section><SectionTitle eyebrow='System health' title='Recent audit activity' /><div className='max-h-96 overflow-auto rounded-2xl border' style={{ borderColor: 'var(--border-default)', background: 'var(--bg-surface)' }}><table className='min-w-full text-left text-xs'><thead className='sticky top-0' style={{ background: 'var(--bg-muted)', color: 'var(--text-secondary)' }}><tr><th className='px-4 py-3'>Time</th><th className='px-4 py-3'>Actor</th><th className='px-4 py-3'>Action</th><th className='px-4 py-3'>Entity</th></tr></thead><tbody>{data.recentActivities.map((item) => <tr key={item.id} className='border-t' style={{ borderColor: 'var(--border-default)' }}><td className='whitespace-nowrap px-4 py-3' style={{ color: 'var(--text-secondary)' }}>{new Date(item.occurredAt).toLocaleString()}</td><td className='px-4 py-3 font-semibold' style={{ color: 'var(--text-primary)' }}>{item.actor || 'System'}</td><td className='px-4 py-3'><span className='rounded-full bg-purple-500/10 px-2 py-1 font-bold text-purple-600'>{item.action.replaceAll('_', ' ')}</span></td><td className='px-4 py-3' style={{ color: 'var(--text-secondary)' }}>{item.entityType.replaceAll('_', ' ')}</td></tr>)}</tbody></table>{!data.recentActivities.length && <p className='p-8 text-center text-sm' style={{ color: 'var(--text-tertiary)' }}>No audit activity in this period.</p>}</div></section>; }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className='mb-3'><p className='text-[10px] font-extrabold uppercase tracking-[.18em] text-purple-600'>{eyebrow}</p><h2 className='mt-1 text-lg font-bold' style={{ color: 'var(--text-primary)' }}>{title}</h2></div>; }
function metricIcon(key: string): ReactNode { if (key.includes('employee')) return <Users size={19} />; if (key.includes('project')) return <FolderKanban size={19} />; if (key.includes('task')) return <CheckSquare2 size={19} />; if (key.includes('leave') || key.includes('present') || key.includes('late') || key.includes('absent')) return <CalendarCheck2 size={19} />; if (key.includes('job') || key.includes('application') || key.includes('interview') || key.includes('hire')) return <BriefcaseBusiness size={19} />; if (key.includes('team')) return <UsersRound size={19} />; if (key.includes('notification')) return <Bell size={19} />; if (key.includes('announcement')) return <FileBarChart2 size={19} />; return <BarChart3 size={19} />; }
